[package]
name = "chapter2"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/main.rs"

[[bin]]
name = "smtp"
path = "src/smtp.rs"
